# from name: plasmabio-template-r

name: M2MEG-RNAseq-TP6-7-R
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - nodejs
  - libgomp
  - bowtie
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
  
  # - r-ggplot2
  
